# Funding options for Bagus Browser
# Adicione suas opções de financiamento aqui

# github: [peder1981]
# patreon: username
# ko_fi: username
# custom: ['https://paypal.me/username', 'https://www.buymeacoffee.com/username']
